#!/usr/bin/env node
var ed25519 = require('./ed25519')

var keypair = ed25519.keys()

console.log('export PUBLIC_KEY="' + keypair.publicKey + '"')
console.log('export PRIVATE_KEY="' + keypair.privateKey + '"')
